name: Keep Vercel Active
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive
        run: curl -s https://cybernetic-sabotage.vercel.app/ > /dev/null
